name: Static Build

on: [push]

# TODO: volume and cache
jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: clfoundation/sbcl:alpine3.14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: daewok/sbcl
          path: sbcl-static
          ref: static-executable-v2
      - run: |
          apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg patch zlib-dev zlib-static git
          ls -l
          ls -l ../
          ls -l ~/
