name: Static Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azimut/run-on-arch-action@master
        name: Run commands
        id: runcmd
        with:
          arch: i386
          distro: alpine_latest
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg patch zlib-dev zlib-static git tar bash xz openssh-client-common zstd musl-dbg sbcl
            export SBCL_ARCH=x86
            mkdir ~/build
            cd ~/build/
            git clone -b static-executable-v2-2.1.10 https://github.com/daewok/sbcl
            cd -
            cd ~/build/sbcl/
            git fetch
            sh make.sh --fancy --with-sb-linkable-runtime --with-sb-prelink-linkage-table
            mkdir -vp ~/build/binary
            INSTALL_ROOT=~/build/binary sh install.sh

            wget https://beta.quicklisp.org/quicklisp.lisp
            sh run-sbcl.sh --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)'

            cd -
            cd bin/
            ls -l ~/build/binary/ ~/build/binary/lib ~/build/binary/*
            make static SBCL="$HOME/build/binary/bin/sbcl" SBCL_HOME="$HOME/build/binary/lib/sbcl"
            cp /tmp/* "/artifacts/"
      - name: Show the artifact
        run: |
          ls -al "${PWD}/artifacts"

      - uses: actions/upload-artifact@v2
        with:
          name: sbcl-static-gmp
          path: |
            artifacts
          if-no-files-found: error

