name: Static Build

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: clfoundation/sbcl:alpine3.14
    steps:
      - uses: actions/checkout@v2
      # CACHE
      - run: mkdir -pv ~/build
      - name: Get Current Month
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache SBCL 2.1.9 Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-alpine-static-sbcl-2.1.9
        with:
          path: |
            ~/build
            ~/quicklisp
            ~/.cache/common-lisp
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"

      # BUILD
      - name: APK build deps
        run: |
          apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg patch zlib-dev zlib-static git tar bash xz openssh-client-common openssh-client-common
      - name: Build SBCL 2.1.9
        run: |
          export SBCL_ARCH=x86-64
          cd ~/build/
          git clone -b static-executable-v2-2.1.9 https://github.com/daewok/sbcl
          cd sbcl/
          git fetch
          sh make.sh --fancy --with-sb-linkable-runtime --with-sb-prelink-linkage-table
          mkdir -vp ~/build/binary
          INSTALL_ROOT=~/build/binary sh install.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install quicklisp
        run: |
          cd ~/build/sbcl
          wget https://beta.quicklisp.org/quicklisp.lisp
          sh run-sbcl.sh --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)' \
               --eval '(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt" :replace t :prompt nil)'
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build SDL 2.0.12
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ~/Downloads
          wget https://www.libsdl.org/release/SDL2-2.0.12.tar.gz
          tar xzf SDL2-2.0.12.tar.gz
          cd SDL2-2.0.12
          ./configure
          make
      - name: Install SDL 2.0.12
        run: |
          cd ~/Downloads/SDL2-2.0.12
          make install

      # Step 0: gather deps
      - name: apk deps
        run: |
          cd ~/build
          apk add --no-cache imagemagick-dev imagemagick-static | tee apks.log
          apk add --no-cache --force-broken-world $(cat ~/build/apks.log | grep Installing | cut -f3 -d' ' | fgrep -v -- '-dev' | sort | uniq | sed 's#$#-dev#g')
          apk add --no-cache --force-broken-world bzip2-static $(cat ~/build/apks.log | grep Installing | cut -f3 -d' ' | fgrep -v -- '-dev' | fgrep -v -- '-static' | sort | uniq | sed 's#$#-static#g')
          ls -l /usr/lib/libMagi*

      - name: Get LISP deps
        run: |
          cd /usr/lib
          ln -s libMagickWand-7.Q16HDRI.so libMagickWand.so
          cd ~/quicklisp/local-projects/
          (test -d lisp-magick-wand) || git clone --depth=1 https://github.com/ruricolist/lisp-magick-wand/
          ( cd lisp-magick-wand/ ; git pull )

      # STEP 1: Dump after (require)
      - name: Load into an image
        run: |
          cd ~/build/sbcl
          sh run-sbcl.sh --non-interactive \
            --eval '(ql:quickload :deploy)' \
            --eval '(require :asdf)' \
            --load /__w/water/water/water.asd \
            --eval '(ql:quickload :water)' \
            --load tools-for-build/dump-linkage-info.lisp \
            --eval '(sb-dump-linkage-info:dump-to-file "/tmp/linkage-info.sexp")' \
            --eval '(sb-ext:save-lisp-and-die "/tmp/sb-gmp-tester.core")'
          ls -l /tmp

      # STEP 2: Link -l
      - name: Build static runtime
        run: |
          cat ~/build/binary/lib/sbcl/sbcl.mk
          cd ~/build/sbcl
          sh run-sbcl.sh --script tools-for-build/create-linkage-table-prelink-info-override.lisp \
              /tmp/linkage-info.sexp \
              /tmp/linkage-table-prelink-info-override.c
          ls -l /tmp
          while read l; do \
            echo "$l"; eval "export ${l%%=*}=\"${l#*=}\""; \
          done < ~/build/binary/lib/sbcl/sbcl.mk
          env
          $CC $CFLAGS -Wno-builtin-declaration-mismatch -o /tmp/linkage-table-prelink-info-override.o -c /tmp/linkage-table-prelink-info-override.c
          $CC -no-pie -static $LINKFLAGS -o /tmp/static-sbcl ~/build/binary/lib/sbcl/$LIBSBCL /tmp/linkage-table-prelink-info-override.o $(pkg-config --libs MagickWand,sdl2,gl --static) $LIBS
          ls -l /tmp

      # STEP 3: Dump
      - name: Setup :toplevel
        run: |
          /tmp/static-sbcl \
            --core /tmp/sb-gmp-tester.core \
            --non-interactive \
            --eval '(sb-ext:save-lisp-and-die "/tmp/sb-gmp-tester" :executable t :toplevel (lambda () (water:start)) :compression t)'
          ls -l /tmp

      - uses: actions/upload-artifact@v2
        with:
          name: sbcl-static-gmp
          path: |
            /tmp
          if-no-files-found: error

      - name: setup upterm session
        #uses: lhotari/action-upterm@v1
        #uses: mxschmitt/action-tmate@v3
        uses: seemethere/action-tmate@skip_dependency_installation
        if: ${{ failure() }}
        with:
          install_dependencies: false
          sudo: false

