name: Static Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: kozross/run-on-arch-action@master
        name: Run commands
        id: runcmd
        with:
          arch: 386
          distro: alpine
          githubToken: ${{ github.token }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
