name: Static Build

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: clfoundation/sbcl:alpine3.14
    steps:
      - uses: actions/checkout@v2
      # CACHE
      - run: mkdir -pv ~/build
      - name: Get Current Month
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache SBCL 2.1.9 Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-alpine-static-sbcl-2.1.9
        with:
          path: |
            ~/build/
            ~/.cache/common-lisp/
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"

      # BUILD
      - name: APK build deps
        run: |
          apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg patch zlib-dev zlib-static git tar
      - name: Build SBCL 2.1.9
        run: |
          export SBCL_ARCH=x86-64
          cd ~/build/
          git clone -b static-executable-v2-2.1.9 https://github.com/daewok/sbcl
          cd sbcl/
          git fetch
          sh make.sh --fancy --with-sb-linkable-runtime --with-sb-prelink-linkage-table
          mkdir -vp ~/build/binary
          INSTALL_ROOT=~/build/binary sh install.sh
        if: steps.cache.outputs.cache-hit != 'true'

      # STEP 1: Dump after (require)
      - name: Load into an image
        run: |
          ls -l /__w/water/water/water.asd
          apk add --no-cache imagemagick-dev sdl2-dev
          cd ~/build/sbcl
          sh run-sbcl.sh --non-interactive \
            --eval '(require :asdf)' \
            --load /__w/water/water/water.asd \
            --eval '(ql:quickload :water)' \
            --load tools-for-build/dump-linkage-info.lisp \
            --eval '(sb-dump-linkage-info:dump-to-file "/tmp/linkage-info.sexp")' \
            --eval '(sb-ext:save-lisp-and-die "/tmp/sb-gmp-tester.core")'
          ls -l /tmp

      # STEP 2: Link -l
      - name: Build static runtime
        run: |
          cd ~/build/sbcl
          sh run-sbcl.sh --script tools-for-build/create-linkage-table-prelink-info-override.lisp \
              /tmp/linkage-info.sexp \
              /tmp/linkage-table-prelink-info-override.c
          ls -l /tmp
          while read l; do \
            eval "${l%%=*}=\"${l#*=}\""; \
          done < ~/build/binary/lib/sbcl/sbcl.mk
          env
          $CC $CFLAGS -Wno-builtin-declaration-mismatch -o /tmp/linkage-table-prelink-info-override.o -c /tmp/linkage-table-prelink-info-override.c
          $CC -no-pie -static $LINKFLAGS -o /tmp/static-sbcl ~/build/binary/lib/sbcl/$LIBSBCL /tmp/linkage-table-prelink-info-override.o -l $(pkg-config --libs MagickWand,sdl2 --static) $LIBS
          ls -l /tmp

      # STEP 3: Dump
      - name: Setup :toplevel
        run: |
          /tmp/static-sbcl \
            --core /tmp/sb-gmp-tester.core \
            --non-interactive \
            --eval '(sb-ext:save-lisp-and-die "/tmp/sb-gmp-tester" :executable t :toplevel (lambda () (water:start)) :compression t)'
          ls -l /tmp

      - uses: actions/upload-artifact@v2
        with:
          name: sbcl-static-gmp
          path: |
            /tmp
          if-no-files-found: error
