name: Static Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azimut/run-on-arch-action@master
        name: Run commands
        id: runcmd
        with:
          arch: i386
          distro: alpine_latest
          run: |
            uname -m
            echo ::set-output name=uname::$(uname -m)
      - uses: azimut/run-on-arch-action@master
        name: Run commands
        id: runcm
        with:
          arch: armv7
          distro: ubuntu18.04
          run: |
            uname -m
            echo ::set-output name=uname::$(uname -m)
      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcm.outputs.uname }}"
